-- Inserimento prodotti
INSERT INTO prodotto (nome, prezzo, anno, marca, tipologia, descrizione) VALUES 
('iPhone 16 Pro Max', 1232.49, 2024, 'Apple', 'SMARTPHONE', 'Smartphone di fascia alta rilasciato nel 2024. Disponibile in nero titanio, bianco titanio, titanio naturale e titanio blu. Monta il chip A18 Pro. Il display è un Super Retina XDR da 6.9 pollici con tecnologia ProMotion. Dispone di un sistema di fotocamere Pro, inclusa una fotocamera principale da 48MP, un teleobiettivo con zoom ottico 5x e un grandangolo. La batteria offre fino a 29 ore di riproduzione video. La memoria RAM parte da 8 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 1 TB.'),
('iPhone 16 Pro', 1147.49, 2024, 'Apple', 'SMARTPHONE', 'Smartphone di fascia alta rilasciato nel 2024. Disponibile in nero titanio, bianco titanio, titanio naturale e titanio blu. È alimentato dal chip A18 Pro. Il display è un Super Retina XDR da 6.3 pollici con tecnologia ProMotion. Presenta un sistema di fotocamere Pro con una fotocamera principale da 48MP, un teleobiettivo con zoom ottico 5x e un grandangolo. La batteria garantisce fino a 24 ore di riproduzione video. La memoria RAM è di 8 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 1 TB.'),
('iPhone 16 Plus', 892.49, 2024, 'Apple', 'SMARTPHONE', 'Smartphone rilasciato nel 2024. Le colorazioni disponibili sono nero, blu, verde, rosa e giallo. Monta il chip A18. Il display è un Super Retina XDR da 6.7 pollici. Il sistema a doppia fotocamera include una fotocamera principale da 48MP e un grandangolo. La batteria offre un''autonomia fino a 26 ore di riproduzione video. La memoria RAM è di 6 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 512 GB.'),
('iPhone 16', 807.49, 2024, 'Apple', 'SMARTPHONE', 'Smartphone rilasciato nel 2024. Disponibile in nero, blu, verde, rosa e giallo. È alimentato dal chip A18. Il display è un Super Retina XDR da 6.1 pollici. Ha un sistema a doppia fotocamera con una fotocamera principale da 48MP e un grandangolo. La batteria dura fino a 20 ore di riproduzione video. La memoria RAM è di 6 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 512 GB.'),
('iPhone 15 Pro Max', 722.49, 2023, 'Apple', 'SMARTPHONE', 'Smartphone di fascia alta rilasciato nel 2023. Disponibile in titanio nero, titanio bianco, titanio blu e titanio naturale. Monta il chip A17 Pro. Il display è un Super Retina XDR da 6.7 pollici con tecnologia ProMotion. Dispone di un sistema di fotocamere Pro, inclusa una fotocamera principale da 48MP, un teleobiettivo con zoom ottico 5x e un grandangolo. La batteria garantisce fino a 29 ore di riproduzione video. La memoria RAM è di 8 GB e lo spazio di archiviazione parte da 256 GB, espandibile fino a 1 TB.'),
('iPhone 15 Pro', 764.99, 2023, 'Apple', 'SMARTPHONE', 'Smartphone di fascia alta rilasciato nel 2023. Disponibile in titanio nero, titanio bianco, titanio blu e titanio naturale. È alimentato dal chip A17 Pro. Il display è un Super Retina XDR da 6.1 pollici con tecnologia ProMotion. Presenta un sistema di fotocamere Pro con una fotocamera principale da 48MP, un teleobiettivo con zoom ottico 3x e un grandangolo. La batteria dura fino a 23 ore di riproduzione video. La memoria RAM è di 8 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 1 TB.'),
('iPhone 15 Plus', 637.49, 2023, 'Apple', 'SMARTPHONE', 'Smartphone rilasciato nel 2023. Le colorazioni disponibili sono nero, blu, verde, giallo e rosa. Monta il chip A16 Bionic. Il display è un Super Retina XDR da 6.7 pollici. Il sistema a doppia fotocamera include una fotocamera principale da 48MP e un grandangolo. La batteria offre un''autonomia fino a 26 ore di riproduzione video. La memoria RAM è di 6 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 512 GB.'),
('iPhone 15', 509.99, 2023, 'Apple', 'SMARTPHONE', 'Smartphone rilasciato nel 2023. Disponibile in nero, blu, verde, giallo e rosa. È alimentato dal chip A16 Bionic. Il display è un Super Retina XDR da 6.1 pollici. Ha un sistema a doppia fotocamera con una fotocamera principale da 48MP e un grandangolo. La batteria dura fino a 20 ore di riproduzione video. La memoria RAM è di 6 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 512 GB.'),
('iPhone 14 Pro Max', 578.49, 2022, 'Apple', 'SMARTPHONE', 'Smartphone di fascia alta rilasciato nel 2022. Disponibile in viola scuro, oro, argento e nero siderale. Monta il chip A16 Bionic. Il display è un Super Retina XDR da 6.7 pollici con tecnologia ProMotion. Dispone di un sistema di fotocamere Pro, inclusa una fotocamera principale da 48MP, un teleobiettivo con zoom ottico 3x e un grandangolo. La batteria offre fino a 29 ore di riproduzione video. La memoria RAM è di 6 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 1 TB.'),
('iPhone 14 Pro', 505.49, 2022, 'Apple', 'SMARTPHONE', 'Smartphone di fascia alta rilasciato nel 2022. Disponibile in viola scuro, oro, argento e nero siderale. È alimentato dal chip A16 Bionic. Il display è un Super Retina XDR da 6.1 pollici con tecnologia ProMotion. Presenta un sistema di fotocamere Pro con una fotocamera principale da 48MP, un teleobiettivo con zoom ottico 3x e un grandangolo. La batteria dura fino a 23 ore di riproduzione video. La memoria RAM è di 6 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 1 TB.'),
('iPhone 14 Plus', 396.99, 2022, 'Apple', 'SMARTPHONE', 'Smartphone rilasciato nel 2022. Le colorazioni disponibili sono mezzanotte, viola, galassia, rosso (PRODUCT)RED, blu e giallo. Monta il chip A15 Bionic. Il display è un Super Retina XDR da 6.7 pollici. Il sistema a doppia fotocamera include una fotocamera principale da 12MP e un grandangolo. La batteria offre un''autonomia fino a 26 ore di riproduzione video. La memoria RAM è di 6 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 512 GB.'),
('iPhone 14', 324.49, 2022, 'Apple', 'SMARTPHONE', 'Smartphone rilasciato nel 2022. Disponibile in mezzanotte, viola, galassia, rosso (PRODUCT)RED, blu e giallo. È alimentato dal chip A15 Bionic. Il display è un Super Retina XDR da 6.1 pollici. Ha un sistema a doppia fotocamera con una fotocamera principale da 12MP e un grandangolo. La batteria dura fino a 20 ore di riproduzione video. La memoria RAM è di 6 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 512 GB.'),
('Samsung Galaxy S25 Ultra', 1099.99, 2025, 'Samsung', 'SMARTPHONE', 'Smartphone di fascia alta rilasciato nel 2025. Presenta una scocca in titanio e colorazioni come nero, grigio, blu e verde. Monta il processore Snapdragon 8 Gen 5 o Exynos 2500. Il display è un Dynamic AMOLED 2X da 6.8 pollici. Il sistema di fotocamere posteriori include un sensore principale da 200MP, un teleobiettivo periscopico e un grandangolo. Supporta la ricarica rapida e la ricarica wireless. La memoria RAM parte da 12 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 1 TB.'),
('Samsung Galaxy S25+', 899.99, 2025, 'Samsung', 'SMARTPHONE', 'Smartphone rilasciato nel 2025. Disponibile in nero, grigio e blu. È alimentato dal processore Snapdragon 8 Gen 5 o Exynos 2500. Il display è un Dynamic AMOLED 2X da 6.6 pollici. Il sistema di fotocamere posteriori include un sensore principale e un grandangolo. La batteria supporta la ricarica rapida. La memoria RAM parte da 8 GB e lo spazio di archiviazione da 128 GB, espandibile fino a 512 GB.'),
('Samsung Galaxy S25', 749.99, 2025, 'Samsung', 'SMARTPHONE', 'Smartphone rilasciato nel 2025. Disponibile in nero, grigio e blu. Monta il processore Snapdragon 8 Gen 5 o Exynos 2500. Il display è un Dynamic AMOLED 2X da 6.2 pollici. Il sistema di fotocamere posteriori include un sensore principale e un grandangolo. La batteria supporta la ricarica rapida. La memoria RAM parte da 8 GB e lo spazio di archiviazione da 128 GB, espandibile fino a 512 GB.'),
('Samsung Galaxy S24 Ultra', 1232.49, 2024, 'Samsung', 'SMARTPHONE', 'Smartphone di fascia alta rilasciato nel 2024. Presenta una scocca in titanio e colorazioni come grigio, nero, viola e giallo. Monta il processore Snapdragon 8 Gen 3 for Galaxy. Il display è un Dynamic AMOLED 2X da 6.8 pollici. Il sistema di fotocamere posteriori include un sensore principale da 200MP, un teleobiettivo periscopico e un grandangolo. Supporta la ricarica rapida e la ricarica wireless. La memoria RAM parte da 12 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 1 TB.'),
('Samsung Galaxy S24+', 1011.49, 2024, 'Samsung', 'SMARTPHONE', 'Smartphone rilasciato nel 2024. Disponibile in nero, grigio, viola e giallo. È alimentato dal processore Snapdragon 8 Gen 3 for Galaxy o Exynos 2400. Il display è un Dynamic AMOLED 2X da 6.7 pollici. Il sistema di fotocamere posteriori include un sensore principale da 50MP e un grandangolo. La batteria supporta la ricarica rapida. La memoria RAM parte da 12 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 512 GB.'),
('Samsung Galaxy S24', 842.49, 2024, 'Samsung', 'SMARTPHONE', 'Smartphone rilasciato nel 2024. Disponibile in nero, grigio, viola e giallo. Monta il processore Snapdragon 8 Gen 3 for Galaxy o Exynos 2400. Il display è un Dynamic AMOLED 2X da 6.2 pollici. Il sistema di fotocamere posteriori include un sensore principale da 50MP e un grandangolo. La batteria supporta la ricarica rapida. La memoria RAM parte da 8 GB e lo spazio di archiviazione da 128 GB, espandibile fino a 512 GB.'),
('Samsung Galaxy S23 Ultra', 722.49, 2023, 'Samsung', 'SMARTPHONE', 'Smartphone di fascia alta rilasciato nel 2023. Disponibile in nero, crema, verde e lavanda. Monta il processore Snapdragon 8 Gen 2 for Galaxy. Il display è un Dynamic AMOLED 2X da 6.8 pollici. Il sistema di fotocamere posteriori include un sensore principale da 200MP, un teleobiettivo periscopico e un grandangolo. Supporta la ricarica rapida e la ricarica wireless. La memoria RAM parte da 8 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 1 TB.'),
('Samsung Galaxy S23+', 591.49, 2023, 'Samsung', 'SMARTPHONE', 'Smartphone rilasciato nel 2023. Disponibile in nero, crema, verde e lavanda. È alimentato dal processore Snapdragon 8 Gen 2 for Galaxy. Il display è un Dynamic AMOLED 2X da 6.6 pollici. Il sistema di fotocamere posteriori include un sensore principale da 50MP e un grandangolo. La batteria supporta la ricarica rapida. La memoria RAM parte da 8 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 512 GB.'),
('Samsung Galaxy S23', 493.99, 2023, 'Samsung', 'SMARTPHONE', 'Smartphone rilasciato nel 2023. Disponibile in nero, crema, verde e lavanda. Monta il processore Snapdragon 8 Gen 2 for Galaxy. Il display è un Dynamic AMOLED 2X da 6.1 pollici. Il sistema di fotocamere posteriori include un sensore principale da 50MP e un grandangolo. La batteria supporta la ricarica rapida. La memoria RAM parte da 8 GB e lo spazio di archiviazione da 128 GB, espandibile fino a 256 GB.'),
('Samsung Galaxy Z Fold 4', 578.49, 2022, 'Samsung', 'SMARTPHONE', 'Smartphone pieghevole rilasciato nel 2022. Disponibile in grigio-verde, nero phantom e beige. Monta il processore Snapdragon 8+ Gen 1. Il display esterno è un Dynamic AMOLED 2X da 6.2 pollici, mentre quello interno pieghevole è da 7.6 pollici. Dispone di un sistema di fotocamere posteriori di alta qualità. La batteria supporta la ricarica rapida. La memoria RAM è di 12 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 1 TB.'),
('Samsung Galaxy Z Flip 4', 486.49, 2022, 'Samsung', 'SMARTPHONE', 'Smartphone pieghevole a conchiglia rilasciato nel 2022. Disponibile in Bora Purple, Graphite, Pink Gold e Blue. È alimentato dal processore Snapdragon 8+ Gen 1. Il display esterno è un Super AMOLED da 1.9 pollici, mentre quello interno pieghevole è un Dynamic AMOLED 2X da 6.7 pollici. La batteria supporta la ricarica rapida. La memoria RAM è di 8 GB e lo spazio di archiviazione da 128 GB, espandibile fino a 512 GB.'),
('Samsung Galaxy Z Fold 5', 722.49, 2023, 'Samsung', 'SMARTPHONE', 'Smartphone pieghevole rilasciato nel 2023. Disponibile in Icy Blue, Phantom Black, Cream e Graphite. Monta il processore Snapdragon 8 Gen 2 for Galaxy. Il display esterno è un Dynamic AMOLED 2X da 6.2 pollici, mentre quello interno pieghevole è da 7.6 pollici. Dispone di un sistema di fotocamere posteriori di alta qualità. La batteria supporta la ricarica rapida. La memoria RAM è di 12 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 1 TB.'),
('Samsung Galaxy Z Flip 5', 591.49, 2023, 'Samsung', 'SMARTPHONE', 'Smartphone pieghevole a conchiglia rilasciato nel 2023. Disponibile in Menta, Grafite, Crema e Lavanda. È alimentato dal processore Snapdragon 8 Gen 2 for Galaxy. Il display esterno è un Super AMOLED da 3.4 pollici, mentre quello interno pieghevole è un Dynamic AMOLED 2X da 6.7 pollici. La batteria supporta la ricarica rapida. La memoria RAM è di 8 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 512 GB.'),
('Samsung Galaxy Z Fold 6', 1011.49, 2024, 'Samsung', 'SMARTPHONE', 'Smartphone pieghevole rilasciato nel 2024. Disponibile in vari colori. Monta il processore Snapdragon 8 Gen 3 for Galaxy. Il display esterno è un Dynamic AMOLED 2X da 6.3 pollici, mentre quello interno pieghevole è da 7.6 pollici. Dispone di un sistema di fotocamere posteriori di alta qualità. La batteria supporta la ricarica rapida. La memoria RAM parte da 12 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 1 TB.'),
('Samsung Galaxy Z Flip 6', 842.49, 2024, 'Samsung', 'SMARTPHONE', 'Smartphone pieghevole a conchiglia rilasciato nel 2024. Disponibile in vari colori. È alimentato dal processore Snapdragon 8 Gen 3 for Galaxy. Il display esterno è un Super AMOLED da 3.9 pollici, mentre quello interno pieghevole è un Dynamic AMOLED 2X da 6.7 pollici. La batteria supporta la ricarica rapida. La memoria RAM è di 8 GB e lo spazio di archiviazione da 128 GB, espandibile fino a 512 GB.'),
('Samsung Galaxy Z Fold 7', 1799.99, 2025, 'Samsung', 'SMARTPHONE', 'Smartphone pieghevole rilasciato nel 2025. Disponibile in varie colorazioni. Monta il processore Snapdragon 8 Gen 5. Il display esterno è un Dynamic AMOLED 2X da 6.2 pollici, mentre quello interno pieghevole è da 7.6 pollici. Dispone di un sistema di fotocamere posteriori di alta qualità. La batteria supporta la ricarica rapida. La memoria RAM parte da 12 GB e lo spazio di archiviazione da 256 GB, espandibile fino a 1 TB.'),
('Samsung Galaxy Z Flip 7', 1199.99, 2025, 'Samsung', 'SMARTPHONE', 'Smartphone pieghevole a conchiglia rilasciato nel 2025. Disponibile in varie colorazioni. È alimentato dal processore Snapdragon 8 Gen 5. Il display esterno è un Super AMOLED da 3.4 pollici, mentre quello interno pieghevole è un Dynamic AMOLED 2X da 6.7 pollici. La batteria supporta la ricarica rapida. La memoria RAM è di 8 GB e lo spazio di archiviazione da 128 GB, espandibile fino a 512 GB.'),
('Google Pixel 7', 578.49, 2022, 'Google', 'SMARTPHONE', 'Smartphone rilasciato nel 2022. Disponibile in Obsidian, Snow e Lemongrass. È alimentato dal processore Tensor G2. Il display è un OLED da 6.3 pollici. Dispone di un sistema a doppia fotocamera posteriore, con un sensore principale da 50MP. La batteria supporta la ricarica rapida e wireless. La memoria RAM è di 8 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 256 GB.'),
('Google Pixel 7 Pro', 315.29, 2022, 'Google', 'SMARTPHONE', 'Smartphone rilasciato nel 2022. Disponibile in Obsidian, Snow e Hazel. Monta il processore Tensor G2. Il display è un OLED da 6.7 pollici con tecnologia LTPO. Presenta un sistema di fotocamere posteriori avanzato, con un sensore principale da 50MP. La batteria offre un''autonomia elevata e supporta la ricarica rapida e wireless. La memoria RAM è di 12 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 512 GB.'),
('Google Pixel 8', 764.99, 2023, 'Google', 'SMARTPHONE', 'Smartphone rilasciato nel 2023. Disponibile in Obsidian, Hazel e Rose. È alimentato dal processore Tensor G3. Il display è un Actua Display da 6.2 pollici. Dispone di un sistema a doppia fotocamera posteriore, con un sensore principale da 50MP. La batteria supporta la ricarica rapida e wireless. La memoria RAM è di 8 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 256 GB.'),
('Google Pixel 8 Pro', 445.49, 2023, 'Google', 'SMARTPHONE', 'Smartphone rilasciato nel 2023. Disponibile in Obsidian, Porcelain e Bay. Monta il processore Tensor G3. Il display è un Super Actua Display da 6.7 pollici con tecnologia LTPO. Presenta un sistema di fotocamere posteriori avanzato, con un sensore principale da 50MP. La batteria offre un''autonomia elevata e supporta la ricarica rapida e wireless. La memoria RAM è di 12 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 1 TB.'),
('Google Pixel 9', 678.49, 2024, 'Google', 'SMARTPHONE', 'Smartphone rilasciato nel 2024. Disponibile in vari colori. È alimentato dal processore Tensor G4. Il display è un OLED da 6.2 pollici. Dispone di un sistema a doppia fotocamera posteriore. La batteria supporta la ricarica rapida e wireless. La memoria RAM è di 8 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 512 GB.'),
('Google Pixel 9 Pro', 417.49, 2024, 'Google', 'SMARTPHONE', 'Smartphone rilasciato nel 2024. Disponibile in vari colori. Monta il processore Tensor G4. Il display è un OLED da 6.7 pollici con tecnologia LTPO. Presenta un sistema di fotocamere posteriori avanzato, con un sensore principale di ultima generazione. La batteria offre un''autonomia elevata e supporta la ricarica rapida e wireless. La memoria RAM è di 12 GB e lo spazio di archiviazione parte da 128 GB, espandibile fino a 512 GB.'),
('MacBook Air M2', 578.49, 2022, 'Apple', 'COMPUTER', 'Computer portatile rilasciato nel 2022 da Apple nei colori: Argento, Galassia, Grigio siderale e Mezzanotte. Monta un chip M2, con una architettura di partenza che prevede una CPU da 8 core (4 performance core e 4 efficiency core), una GPU da 8 core, un Neural Engine da 16 core. Monta un Display Liquid Retina da 13.6 pollici con tecnologia IPS e luminosità fino a 500 nit. Supporta la ricarica rapida con l’alimentatore USB‑C da 70W . Presenta una porta MagSafe 3 per la ricarica, due porte Thunderbolt / USB 4 e un jack per cuffie da 3,5 mm. La memoria RAM parte da 8 GB, espandibile fino a 24 GB. Lo spazio di archiviazione parte da 256 GB, espandibile fino a 2 TB. La fotocamera frontale è una 1080p FaceTime HD. La batteria ha un''autonomia fino a 18 ore di riproduzione video.'),
('MacBook Pro M2', 578.49, 2022, 'Apple', 'COMPUTER', 'Computer portatile di fascia alta rilasciato nel 2022 da Apple. Disponibile in argento e grigio siderale. Monta un chip M2, con una architettura di partenza che prevede una CPU da 8 core, una GPU da 10 core e un Neural Engine da 16 core. Il display è un Liquid Retina da 13.3 pollici con luminosità fino a 500 nit. Presenta due porte Thunderbolt / USB 4, un jack per cuffie da 3,5 mm e la ricarica USB-C. La memoria RAM unificata parte da 8 GB, espandibile fino a 24 GB. Lo spazio di archiviazione SSD parte da 256 GB, espandibile fino a 2 TB. La fotocamera frontale è una 720p FaceTime HD. La batteria ha un’autonomia fino a 20 ore di riproduzione video.'),
('MacBook Air M3', 722.49, 2023, 'Apple', 'COMPUTER', 'Computer portatile rilasciato nel 2024 da Apple. Disponibile in argento, galassia, grigio siderale e mezzanotte. Monta un chip M3, con una architettura di partenza che prevede una CPU da 8 core (4 performance core e 4 efficiency core), una GPU da 8 core, un Neural Engine da 16 core. Il display è un Liquid Retina da 13.6 pollici con tecnologia IPS e luminosità fino a 500 nit. Supporta la ricarica rapida con l’alimentatore USB‑C da 70W. Presenta una porta MagSafe 3 per la ricarica, due porte Thunderbolt / USB 4 e un jack per cuffie da 3,5 mm. La memoria RAM unificata parte da 8 GB, espandibile fino a 24 GB. Lo spazio di archiviazione SSD parte da 256 GB, espandibile fino a 2 TB. La fotocamera frontale è una 1080p FaceTime HD. La batteria ha un’autonomia fino a 18 ore di riproduzione video.'),
('MacBook Pro M3', 722.49, 2023, 'Apple', 'COMPUTER', 'Computer portatile di fascia alta rilasciato nel 2023 da Apple. Disponibile in argento e grigio siderale. Monta un chip M3, con architettura di partenza che prevede una CPU da 8 core, una GPU da 10 core e un Neural Engine da 16 core. Il display è un Liquid Retina XDR da 14.2 pollici con tecnologia mini-LED e luminosità fino a 1000 nit. Presenta porte Thunderbolt 4, HDMI, slot per schede SDXC e ricarica MagSafe 3. La memoria RAM unificata parte da 8 GB, espandibile fino a 24 GB. Lo spazio di archiviazione SSD parte da 512 GB, espandibile fino a 2 TB. La fotocamera frontale è una 1080p FaceTime HD. La batteria ha un’autonomia fino a 22 ore di riproduzione video.'),
('MacBook Air M4', 1011.49, 2024, 'Apple', 'COMPUTER', 'Computer portatile rilasciato nel 2025 da Apple. Disponibile in argento, galassia, grigio siderale e mezzanotte. Monta un chip M4, con architettura di partenza che prevede una CPU da 8 core e una GPU da 10 core. Il display è un Liquid Retina da 13.6 o 15.3 pollici con luminosità fino a 500 nit. Supporta la ricarica rapida con l’alimentatore USB‑C da 70W. Presenta una porta MagSafe 3 per la ricarica, due porte Thunderbolt / USB 4 e un jack per cuffie da 3,5 mm. La memoria RAM unificata parte da 8 GB, espandibile fino a 24 GB. Lo spazio di archiviazione SSD parte da 256 GB, espandibile fino a 2 TB. La fotocamera frontale è una 1080p FaceTime HD. La batteria ha un’autonomia fino a 18 ore di riproduzione video.'),
('MacBook Pro M4', 1011.49, 2024, 'Apple', 'COMPUTER', 'Computer portatile di fascia alta rilasciato nel 2025 da Apple. Disponibile in argento e grigio siderale. Monta un chip M4, con architettura di partenza che prevede una CPU da 10 o 12 core, una GPU da 16 core e un Neural Engine migliorato da 16 core. Il display è un Liquid Retina XDR da 14.2 o 16.2 pollici con tecnologia mini-LED e luminosità elevata. Presenta porte Thunderbolt 4, HDMI, slot per schede SDXC e ricarica MagSafe 3. La memoria RAM unificata parte da 16 GB, espandibile fino a 128 GB. Lo spazio di archiviazione SSD parte da 512 GB, espandibile fino a 8 TB. La fotocamera frontale è una 1080p FaceTime HD.'),
('Dell XPS 13', 578.49, 2022, 'Dell', 'COMPUTER', 'Computer portatile rilasciato nel 2022. Disponibile in Sky o Umbra. Monta processori Intel Core di 12a generazione (fino a i7). Il display è un InfinityEdge da 13.4 pollici, con opzioni touch o non-touch. Presenta due porte Thunderbolt 4 e un jack per cuffie. La memoria RAM parte da 8 GB, espandibile fino a 32 GB. Lo spazio di archiviazione SSD parte da 256 GB, espandibile fino a 2 TB. La webcam è una HD. La batteria offre un''ottima autonomia per l''uso quotidiano.'),
('Dell XPS 15', 722.49, 2023, 'Dell', 'COMPUTER', 'Computer portatile rilasciato nel 2023. Disponibile in argento platino. Monta processori Intel Core di 13a generazione (fino a i9). Il display è un InfinityEdge da 15.6 pollici, con opzioni touch o non-touch. Presenta un''ampia selezione di porte, tra cui Thunderbolt 4. La memoria RAM parte da 16 GB, espandibile fino a 64 GB. Lo spazio di archiviazione SSD parte da 512 GB, espandibile fino a 4 TB. La webcam è una HD. La batteria offre un''ottima autonomia.'),
('Dell XPS 17', 1011.49, 2024, 'Dell', 'COMPUTER', 'Computer portatile rilasciato nel 2023. Disponibile in argento platino. Monta processori Intel Core di 13a generazione (fino a i9). Il display è un InfinityEdge da 17 pollici, con opzioni touch o non-touch. Presenta un''ampia selezione di porte, tra cui Thunderbolt 4. La memoria RAM parte da 16 GB, espandibile fino a 64 GB. Lo spazio di archiviazione SSD parte da 512 GB, espandibile fino a 4 TB. La webcam è una HD. La batteria offre un''ottima autonomia.'),
('Dell Latitude 9440 2-in-1', 722.49, 2023, 'Dell', 'COMPUTER', 'Computer portatile convertibile 2-in-1 rilasciato nel 2023. Monta processori Intel Core di 13a generazione. Il display è un InfinityEdge da 14 pollici. Può essere usato come laptop o come tablet. La memoria RAM parte da 16 GB, espandibile fino a 64 GB. Lo spazio di archiviazione SSD parte da 256 GB, espandibile fino a 2 TB. La webcam è una Full HD. La batteria offre una lunga durata per l''uso in mobilità.'),
('Dell G15 Gaming Laptop', 722.49, 2023, 'Dell', 'COMPUTER', 'Computer portatile da gioco rilasciato nel 2023. Disponibile in vari colori. Monta processori Intel Core di 13a generazione o AMD Ryzen. Il display è un 15.6 pollici, con opzioni di refresh rate elevato. Presenta un''ampia selezione di porte. La memoria RAM parte da 16 GB, espandibile fino a 32 GB. Lo spazio di archiviazione SSD parte da 512 GB. La webcam è una HD. La batteria offre una durata sufficiente per sessioni di gioco prolungate.'),
('HP Spectre x360 14', 722.49, 2023, 'HP', 'COMPUTER', 'Computer portatile convertibile 2-in-1 rilasciato nel 2023. Disponibile in Nightfall Black e Nocturne Blue. Monta processori Intel Core di 13a generazione. Il display è un OLED touch da 14 pollici. Può essere usato come laptop o come tablet. La memoria RAM parte da 16 GB, espandibile fino a 32 GB. Lo spazio di archiviazione SSD parte da 512 GB, espandibile fino a 2 TB. La webcam è una Full HD. La batteria garantisce un''ottima autonomia.'),
('HP Envy x360 15', 578.49, 2022, 'HP', 'COMPUTER', 'Computer portatile convertibile 2-in-1 rilasciato nel 2023. Disponibile in varie colorazioni. Monta processori Intel Core di 13a generazione o AMD Ryzen. Il display è un touch da 15.6 pollici. Può essere usato come laptop o come tablet. La memoria RAM parte da 8 GB, espandibile fino a 16 GB. Lo spazio di archiviazione SSD parte da 256 GB, espandibile fino a 1 TB. La webcam è una Full HD. La batteria offre un''ottima autonomia.'),
('HP Omen 16 Gaming Laptop', 722.49, 2023, 'HP', 'COMPUTER', 'Computer portatile da gioco rilasciato nel 2023. Disponibile in nero. Monta processori Intel Core di 13a generazione o AMD Ryzen. Il display è un 16.1 pollici, con opzioni di refresh rate elevato. Presenta un''ampia selezione di porte. La memoria RAM parte da 16 GB, espandibile fino a 32 GB. Lo spazio di archiviazione SSD parte da 512 GB, espandibile fino a 2 TB. La webcam è una HD. La batteria offre una durata sufficiente per sessioni di gioco prolungate.'),
('HP Chromebook x360 14c', 578.49, 2022, 'HP', 'COMPUTER', 'Chromebook convertibile 2-in-1 rilasciato nel 2022. Disponibile in varie colorazioni. Monta processori Intel Core di 11a generazione. Il display è un touch da 14 pollici. Può essere usato come laptop o come tablet. La memoria RAM è di 8 GB. Lo spazio di archiviazione eMMC è di 64 GB, espandibile tramite schede microSD. La webcam è una HD. La batteria offre un''ottima autonomia.'),
('Lenovo Yoga 9i', 722.49, 2023, 'Lenovo', 'COMPUTER', 'Computer portatile convertibile 2-in-1 rilasciato nel 2023. Disponibile in Storm Grey e Oatmeal. Monta processori Intel Core di 13a generazione. Il display è un OLED da 14 pollici. Può essere usato come laptop o come tablet. La memoria RAM parte da 16 GB, espandibile fino a 32 GB. Lo spazio di archiviazione SSD parte da 512 GB, espandibile fino a 1 TB. La webcam è una Full HD. La batteria offre un''ottima autonomia.'),
('Lenovo ThinkPad X1 Carbon Gen 11', 722.49, 2023, 'Lenovo', 'COMPUTER', 'Computer portatile da ufficio rilasciato nel 2023. Disponibile in nero. Monta processori Intel Core di 13a generazione. Il display è un 14 pollici con varie opzioni di risoluzione. Presenta un''ampia selezione di porte, tra cui Thunderbolt 4. La memoria RAM parte da 16 GB, espandibile fino a 32 GB. Lo spazio di archiviazione SSD parte da 256 GB, espandibile fino a 2 TB. La webcam è una Full HD. La batteria garantisce un''ottima autonomia per l''uso professionale.'),
('Lenovo Legion 5i Pro Gen 8', 722.49, 2023, 'Lenovo', 'COMPUTER', 'Computer portatile da gioco rilasciato nel 2023. Disponibile in grigio. Monta processori Intel Core di 13a generazione. Il display è un 16 pollici con risoluzione elevata e refresh rate elevato. Presenta un''ampia selezione di porte. La memoria RAM parte da 16 GB, espandibile fino a 32 GB. Lo spazio di archiviazione SSD parte da 512 GB, espandibile fino a 2 TB. La webcam è una Full HD. La batteria offre una durata sufficiente per sessioni di gioco prolungate.'),
('Lenovo Chromebook Duet 5', 578.49, 2022, 'Lenovo', 'COMPUTER', 'Chromebook 2-in-1 staccabile rilasciato nel 2022. Disponibile in Storm Gray e Abyss Blue. Monta un processore Qualcomm Snapdragon 7c Gen 2. Il display è un OLED touch da 13.3 pollici. La tastiera può essere staccata per usarlo come tablet. La memoria RAM è di 4 GB. Lo spazio di archiviazione eMMC è di 64 GB, espandibile tramite schede microSD. La webcam frontale è una 5MP, quella posteriore è una 8MP. La batteria offre un''ottima autonomia.'),
('iPad 10a generazione', 324.49, 2022, 'Apple', 'TABLET', 'Tablet rilasciato nel 2022. Disponibile in argento, rosa, blu e giallo. Monta un chip A14 Bionic. Il display è un Liquid Retina da 10.9 pollici. Presenta una fotocamera frontale con ultra-grandangolo da 12MP e una fotocamera posteriore da 12MP. Supporta la Apple Pencil (1ª generazione) e la Magic Keyboard Folio. La batteria ha un’autonomia fino a 10 ore.'),
('iPad Air 5a generazione', 505.49, 2022, 'Apple', 'TABLET', 'Tablet rilasciato nel 2022. Disponibile in azzurro, rosa, galassia, viola e grigio siderale. Monta un chip M1. Il display è un Liquid Retina da 10.9 pollici. Presenta una fotocamera frontale con ultra-grandangolo da 12MP e una fotocamera posteriore da 12MP. Supporta l’Apple Pencil (2ª generazione) e la Magic Keyboard. La batteria ha un’autonomia fino a 10 ore.'),
('iPad Pro M2', 724.99, 2022, 'Apple', 'TABLET', 'Tablet di fascia alta rilasciato nel 2022. Disponibile in argento e grigio siderale. Monta un chip M2 con una CPU da 8 core e una GPU da 10 core. Il display è un Liquid Retina XDR da 12.9 pollici o un Liquid Retina da 11 pollici. Presenta una fotocamera frontale con ultra-grandangolo, una fotocamera posteriore da 12MP, e sensore LiDAR. Supporta l’Apple Pencil (2ª generazione) e la Magic Keyboard. La batteria ha un’autonomia fino a 10 ore.'),
('iPad Mini 6a generazione', 235.90, 2021, 'Apple', 'TABLET', 'Tablet rilasciato nel 2022. Disponibile in galassia, rosa, viola e grigio siderale. Monta un chip A15 Bionic. Il display è un Liquid Retina da 8.3 pollici. Presenta una fotocamera frontale con ultra-grandangolo da 12MP e una fotocamera posteriore da 12MP. Supporta l’Apple Pencil (2ª generazione). La batteria ha un’autonomia fino a 10 ore.'),
('iPad Air M2', 388.49, 2022, 'Apple', 'TABLET', 'Tablet rilasciato nel 2024. Disponibile in blu, galassia, grigio siderale e viola. Monta il chip M2 con una CPU da 8 core e una GPU da 10 core. Il display è un Liquid Retina da 11 o 13 pollici. Presenta una fotocamera frontale con ultra-grandangolo in orizzontale e una fotocamera posteriore da 12MP. Supporta la Apple Pencil (USB-C) e la Magic Keyboard. La batteria ha un’autonomia fino a 10 ore.'),
('iPad Pro M4', 799.99, 2024, 'Apple', 'TABLET', 'Tablet di fascia alta rilasciato nel 2024. Disponibile in argento e grigio siderale. Monta un chip M4 con una CPU da 9 o 10 core e una GPU da 10 core. Il display è un Ultra Retina XDR da 11 o 13 pollici. Presenta una fotocamera frontale con ultra-grandangolo in orizzontale, una fotocamera posteriore da 12MP, e sensore LiDAR. Supporta l’Apple Pencil Pro e la Magic Keyboard.'),
('Samsung Galaxy Tab S8', 578.49, 2022, 'Samsung', 'TABLET', 'Tablet rilasciato nel 2022. Disponibile in grigio. Monta il processore Snapdragon 8 Gen 1. Il display è un Super AMOLED da 11 pollici. Supporta la S Pen. La batteria offre un''autonomia sufficiente per l''uso quotidiano.'),
('Samsung Galaxy Tab S8+', 578.49, 2022, 'Samsung', 'TABLET', 'Tablet rilasciato nel 2022. Disponibile in grigio. Monta il processore Snapdragon 8 Gen 1. Il display è un Super AMOLED da 12.4 pollici. Supporta la S Pen. La batteria garantisce un''ottima autonomia.'),
('Samsung Galaxy Tab S8 Ultra', 578.49, 2022, 'Samsung', 'TABLET', 'Tablet di fascia alta rilasciato nel 2022. Disponibile in grigio. Monta il processore Snapdragon 8 Gen 1. Il display è un Super AMOLED da 14.6 pollici. Supporta la S Pen. La batteria garantisce un''autonomia prolungata.'),
('Samsung Galaxy Tab S9', 722.49, 2023, 'Samsung', 'TABLET', 'Tablet rilasciato nel 2023. Disponibile in grigio. Monta il processore Snapdragon 8 Gen 2 for Galaxy. Il display è un Dynamic AMOLED 2X da 11 pollici. Supporta la S Pen. La batteria offre un''autonomia sufficiente per l''uso quotidiano.'),
('Samsung Galaxy Tab S9+', 722.49, 2023, 'Samsung', 'TABLET', 'Tablet rilasciato nel 2023. Disponibile in grigio. Monta il processore Snapdragon 8 Gen 2 for Galaxy. Il display è un Dynamic AMOLED 2X da 12.4 pollici. Supporta la S Pen. La batteria garantisce un''ottima autonomia.'),
('Samsung Galaxy Tab S9 Ultra', 722.49, 2023, 'Samsung', 'TABLET', 'Tablet di fascia alta rilasciato nel 2023. Disponibile in grigio. Monta il processore Snapdragon 8 Gen 2 for Galaxy. Il display è un Dynamic AMOLED 2X da 14.6 pollici. Supporta la S Pen. La batteria garantisce un''autonomia prolungata.'),
('Samsung Galaxy Tab S10', 1011.49, 2024, 'Samsung', 'TABLET', 'Tablet rilasciato nel 2025. Disponibile in vari colori. Monta il processore Snapdragon 8 Gen 5. Il display è un Dynamic AMOLED 2X da 11 pollici. Supporta la S Pen. La batteria offre un''autonomia sufficiente per l''uso quotidiano.'),
('Samsung Galaxy Tab S10+', 1011.49, 2024, 'Samsung', 'TABLET', 'Tablet rilasciato nel 2025. Disponibile in vari colori. Monta il processore Snapdragon 8 Gen 5. Il display è un Dynamic AMOLED 2X da 12.4 pollici. Supporta la S Pen. La batteria garantisce un''ottima autonomia.'),
('Samsung Galaxy Tab S10 Ultra', 1011.49, 2024, 'Samsung', 'TABLET', 'Tablet di fascia alta rilasciato nel 2025. Disponibile in vari colori. Monta il processore Snapdragon 8 Gen 5. Il display è un Dynamic AMOLED 2X da 14.6 pollici. Supporta la S Pen. La batteria ha una capacità elevata che garantisce un''autonomia prolungata.'),
('AirPods Pro 2a gen', 279.99, 2024, 'Apple', 'AUDIO', 'Auricolari true wireless rilasciati nel 2022 da Apple. Presentano audio spaziale personalizzato, cancellazione attiva del rumore e modalità trasparenza. La custodia di ricarica supporta il Find My e l''altoparlante integrato.'),
('Samsung Galaxy Buds2 Pro', 184.25, 2022, 'Samsung', 'AUDIO', 'Auricolari true wireless rilasciati nel 2022. Offrono audio Hi-Fi a 24-bit e cancellazione attiva del rumore. Presentano un design compatto e sono resistenti all''acqua.'),
('Google Pixel Buds Pro', 184.25, 2022, 'Google', 'AUDIO', 'Guricolari true wireless rilasciati nel 2022. Dispongono di cancellazione attiva del rumore e offrono un''esperienza audio ricca. Si integrano perfettamente con i dispositivi Android.'),
('Sony WH-1000XM5', 263.99, 2022, 'Sony', 'AUDIO', 'Cuffie wireless over-ear rilasciate nel 2022. Offrono una cancellazione del rumore all''avanguardia e una qualità audio eccezionale. Presentano un design leggero e un''autonomia della batteria fino a 30 ore.'),
('Sony PlayStation 3D Pulse', 128.30, 2020, 'Sony', 'AUDIO', 'Cuffie wireless over-ear rilasciate nel 2022, progettate per PlayStation 5. Offrono un audio 3D preciso e un''ottima esperienza di gioco. La batteria ha un''autonomia di circa 12 ore.'),
('Bose QuietComfort 45', 263.99, 2022, 'Bose', 'AUDIO', 'Cuffie wireless over-ear rilasciate nel 2022. Offrono una cancellazione del rumore eccellente e un AUDIO bilanciato. La batteria ha un''autonomia fino a 24 ore.'),
('AirPods Max', 395.99, 2022, 'Apple', 'AUDIO', 'Cuffie wireless over-ear rilasciate nel 2022. Offrono audio ad alta fedeltà, cancellazione attiva del rumore e audio spaziale. La custodia Smart Case le mantiene in modalità a basso consumo.'),
('Beats Studio3 Wireless', 163.28, 2021, 'Beats', 'AUDIO', 'Cuffie wireless over-ear rilasciate nel 2022. Offrono un''esperienza di ascolto di alta qualità e una cancellazione adattiva del rumore. La batteria ha un''autonomia fino a 22 ore.'),
('Sonos Era 100', 253.99, 2023, 'Sonos', 'AUDIO', 'Smart speaker wireless rilasciato nel 2023. Offre un AUDIO stereo spaziale e un audio di alta qualità in un design compatto. Si può utilizzare singolarmente o in coppia per un effetto stereo.'),
('Sonos Era 300', 423.49, 2023, 'Sonos', 'AUDIO', 'Smart speaker wireless rilasciato nel 2023. Offre un''esperienza audio spaziale cinematografica, con audio surround e supporto Dolby Atmos. Si può utilizzare singolarmente o in coppia'),
('Amazon Echo (4a generazione)', 51.74, 2020, 'Amazon', 'AUDIO', 'Smart speaker rilasciato nel 2022. Presenta un design sferico e offre un AUDIO ricco. Si integra con Alexa e supporta il controllo vocale di musica e dispositivi domestici.'),
('Google Nest Audio', 51.74, 2020, 'Google', 'AUDIO', 'Smart speaker rilasciato nel 2022. Offre un AUDIO ricco e potente. Si integra perfettamente con Google Assistant e supporta il controllo vocale per musica e dispositivi domestici.'),
('HomePod mini', 57.95, 2021, 'Apple', 'AUDIO', 'Smart speaker rilasciato nel 2022. Offre un AUDIO a 360 gradi e si integra con l''ecosistema Apple e Siri. È un assistente domestico intelligente per gestire le attività quotidiane.'),
('Amazon Echo Dot (5a generazione)', 35.99, 2022, 'Amazon', 'AUDIO', 'Smart speaker compatto rilasciato nel 2022. Offre un audio di alta qualità, con bassi più profondi e voci più nitide. Si integra con Alexa e supporta il controllo vocale.'),
('Google Nest Mini (2a generazione)', 29.99, 2020, 'Google', 'AUDIO', 'Smart speaker compatto rilasciato nel 2022. Offre un AUDIO di alta qualità per le sue dimensioni e si integra con Google Assistant. Ideale per ogni stanza della casa.'),
('HomePod (1a generazione)', 161.33, 2018, 'Apple', 'AUDIO', 'Smart speaker rilasciato nel 2022. Offre una qualità audio eccezionale e bassi ricchi. Si integra perfettamente con l''ecosistema Apple e Siri.'),
('PlayStation 5', 230.58, 2020, 'Sony', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. Si presenta con un design futuristico e una scocca bianca e nera. Monta una CPU AMD Zen 2 a 8 core con frequenza fino a 3.5 GHz e una GPU RDNA 2 che offre 10.28 TFLOPS di potenza. L''SSD ad alta velocità da 825 GB garantisce tempi di caricamento quasi istantanei. Offre un''esperienza di gioco in 4K a 60 fps o più e supporta il ray tracing. Dispone di un lettore Blu-ray 4K Ultra HD.'),
('PlayStation 5 Digital Edition', 230.58, 2020, 'Sony', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022, identica al modello standard ma priva di lettore ottico. Monta una CPU AMD Zen 2 a 8 core con frequenza fino a 3.5 GHz e una GPU RDNA 2 che offre 10.28 TFLOPS di potenza. L''SSD ad alta velocità da 825 GB garantisce tempi di caricamento quasi istantanei. I giochi sono disponibili solo in formato digitale tramite PlayStation Store. Offre un''esperienza di gioco in 4K a 60 fps o più e supporta il ray tracing.'),
('PlayStation 5 Pro', 399.99, 2023, 'Sony', 'CONSOLE', 'Console per videogiochi rilasciata nel 2024. Caratterizzata da un design simile a quello del modello standard, ma con un hardware potenziato per prestazioni grafiche superiori. Monta una CPU potenziata e una GPU con una potenza di calcolo superiore ai 30 TFLOPS, che supporta il ray tracing avanzato. Include un''unità SSD da 1 TB. Offre un''esperienza di gioco in 4K a 60 fps o più. Supporta sia i giochi fisici che quelli digitali.'),
('PlayStation 4', 90.52, 2013, 'Sony', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. È la versione base della console. Monta una CPU x86-64 AMD "Jaguar" a 8 core e una GPU AMD che offre 1.84 TFLOPS di potenza. Include un hard disk da 500 GB o 1 TB. Offre un''esperienza di gioco in Full HD. Supporta sia i giochi fisici che quelli digitali.'),
('PlayStation 4 Pro', 179.36, 2016, 'Sony', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. È una versione potenziata della PlayStation 4. Monta una CPU x86-64 AMD "Jaguar" a 8 core e una GPU AMD che offre 4.2 TFLOPS di potenza. Include un hard disk da 1 TB. Supporta l''esperienza di gioco in 4K con upscaling e HDR. Supporta sia i giochi fisici che quelli digitali.'),
('PlayStation 4 Slim', 134.52, 2016, 'Sony', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. È una versione ridotta e più leggera della PlayStation 4. Monta una CPU x86-64 AMD "Jaguar" a 8 core e una GPU AMD che offre 1.84 TFLOPS di potenza. Include un hard disk da 500 GB o 1 TB. Offre un''esperienza di gioco in Full HD. Supporta sia i giochi fisici che quelli digitali.'),
('Xbox Series X', 230.58, 2020, 'Microsoft', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. Si presenta con un design a torre nero opaco. Monta una CPU AMD Zen 2 a 8 core con frequenza fino a 3.8 GHz e una GPU RDNA 2 che offre 12 TFLOPS di potenza. L''unità SSD NVMe da 1 TB garantisce tempi di caricamento molto rapidi. Offre un''esperienza di gioco in 4K a 60 fps o più e supporta il ray tracing. Dispone di un lettore Blu-ray 4K Ultra HD.'),
('Xbox Series S', 138.35, 2020, 'Microsoft', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. È una versione più compatta e priva di lettore ottico della Xbox Series X. Monta una CPU AMD Zen 2 a 8 core con frequenza fino a 3.6 GHz e una GPU RDNA 2 che offre 4 TFLOPS di potenza. L''unità SSD NVMe da 512 GB garantisce tempi di caricamento rapidi. Offre un''esperienza di gioco in 1440p fino a 120 fps. I giochi sono disponibili solo in formato digitale.'),
('Xbox One X', 123.87, 2017, 'Microsoft', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. È una versione potenziata della Xbox One. Monta una CPU AMD "Jaguar" a 8 core con frequenza fino a 2.3 GHz e una GPU AMD che offre 6 TFLOPS di potenza. Include un hard disk da 1 TB. Supporta il gioco in 4K nativo. Dispone di un lettore Blu-ray 4K Ultra HD.'),
('Xbox One S', 89.52, 2016, 'Microsoft', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. È una versione più compatta e leggera della Xbox One. Monta una CPU AMD "Jaguar" a 8 core con frequenza fino a 1.75 GHz e una GPU AMD che offre 1.4 TFLOPS di potenza. Include un hard disk da 500 GB o 1 TB. Supporta la riproduzione di video in 4K e l''HDR. Dispone di un lettore Blu-ray 4K.'),
('Nintendo Switch', 230.58, 2020, 'Nintendo', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. È una console ibrida che può essere usata sia in modalità portatile che su TV. Monta un processore NVIDIA Tegra. Il display è un LCD da 6.2 pollici. I controller staccabili, chiamati Joy-Con, possono essere usati in vari modi. La memoria interna è di 32 GB.'),
('Nintendo Switch Lite', 143.82, 2019, 'Nintendo', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. È una versione più compatta ed economica della Nintendo Switch, pensata esclusivamente per il gioco in modalità portatile. I controller sono integrati nel corpo della console. Monta un processore NVIDIA Tegra. Il display è un LCD da 5.5 pollici. La memoria interna è di 32 GB.'),
('Nintendo Switch OLED', 324.49, 2022, 'Nintendo', 'CONSOLE', 'Console per videogiochi rilasciata nel 2022. È una versione aggiornata della Nintendo Switch. Mantiene la versatilità del modello originale, con la possibilità di giocare sia in modalità portatile che su TV. Il display è un OLED da 7 pollici, che offre colori vivaci e contrasti più elevati. Include un supporto regolabile più robusto, un dock con porta LAN e 64 GB di memoria interna.'),
('Nintendo Switch 2', 349.99, 2024, 'Nintendo', 'CONSOLE', 'Console per videogiochi rilasciata nel 2024. È un''evoluzione della console ibrida originale. Mantiene la versatilità del modello precedente, con la possibilità di giocare sia in modalità portatile che su TV. Si vocifera che monti un processore NVIDIA personalizzato, offrendo prestazioni grafiche superiori e il supporto per il DLSS. Presenta un display più grande e luminoso e Joy-Con riprogettati. La memoria interna è più capiente.'),
('Studio Display', 578.49, 2022, 'Apple', 'MONITOR', 'Monitor rilasciato nel 2022 da Apple. Si presenta con un design sottile in alluminio e un display Retina 5K da 27 pollici. Offre una luminosità di 600 nit e supporta la tecnologia True Tone. Integra una videocamera da 12MP con inquadratura automatica, un sistema audio a sei altoparlanti e tre microfoni in array. Presenta una porta Thunderbolt 3 per il collegamento al Mac e tre porte USB-C per la ricarica e il collegamento di periferiche.'),
('Pro Display XDR', 578.49, 2022, 'Apple', 'MONITOR', 'Monitor professionale rilasciato nel 2022 da Apple. Si presenta con un design in alluminio e un display Retina 6K da 32 pollici. Offre una luminosità di 1000 nit sostenuti e 1600 nit di picco, con un rapporto di contrasto elevato. Supporta un''ampia gamma di colori. Si connette tramite un''unica porta Thunderbolt 3.'),
('LG UltraGear OLED', 722.49, 2023, 'LG', 'MONITOR', 'Monitor rilasciato nel 2023. Si presenta con un display OLED da 27 pollici con risoluzione QHD (2560 x 1440) e un''elevata frequenza di aggiornamento, ideale per il gaming. Offre tempi di risposta ultra-rapidi e neri assoluti. Presenta connettività HDMI e DisplayPort.'),
('Samsung Odyssey Neo G9', 722.49, 2023, 'Samsung', 'MONITOR', 'Monitor curvo rilasciato nel 2023 da Samsung. Si presenta con un display curvo ultra-wide da 49 pollici, con risoluzione DQHD (5120 x 1440). Offre una luminosità di picco di 2000 nit e un''elevata frequenza di aggiornamento.'),
('Samsung ViewFinity S9', 722.49, 2023, 'Samsung', 'MONITOR', 'Monitor rilasciato nel 2023 da Samsung. Si presenta con un display da 27 pollici con risoluzione 5K (5120 x 2880), ideale per i creativi e i professionisti. Offre colori accurati e un''elevata luminosità. Integra una videocamera SlimFit rimovibile.'),
('Dell Alienware AW3423DW', 578.49, 2022, 'Dell', 'MONITOR', 'Monitor curvo rilasciato nel 2022 da Dell. Si presenta con un display QD-OLED da 34 pollici, con risoluzione WQHD (3440 x 1440). Offre un''elevata frequenza di aggiornamento e tempi di risposta rapidi.'),
('LG C3 OLED TV', 722.49, 2023, 'LG', 'TV', 'TV rilasciata nel 2023 da LG. Presenta un display OLED 4K (3840 x 2160) con processore Alpha9 AI Processor Gen6. Supporta il Dolby Vision e il Dolby Atmos. Ideale per il gaming grazie all''elevata frequenza di aggiornamento.'),
('Samsung S95C OLED TV', 722.49, 2023, 'Samsung', 'TV', 'TV rilasciata nel 2023 da Samsung. Presenta un display QD-OLED 4K (3840 x 2160) e un processore Neural Quantum Processor 4K. Offre una luminosità elevata e colori vividi. Supporta il Dolby Atmos.'),
('Samsung QN90C Neo QLED TV', 722.49, 2023, 'Samsung', 'TV', 'TV rilasciata nel 2023 da Samsung. Presenta un display Neo QLED 4K (3840 x 2160) e un processore Neural Quantum Processor 4K. Offre un''elevata luminosità e una gestione precisa della retroilluminazione grazie alla tecnologia Mini LED.'),
('Sony A95K QD-OLED TV', 578.49, 2022, 'Sony', 'TV', 'TV rilasciata nel 2022 da Sony. Presenta un display QD-OLED 4K (3840 x 2160) e un processore Cognitive Processor XR. Offre un''esperienza visiva eccezionale con colori vibranti e contrasti elevati.'),
('Sony Bravia XR A95L OLED', 722.49, 2023, 'Sony', 'TV', 'TV rilasciata nel 2023 da Sony. Presenta un display QD-OLED 4K (3840 x 2160) e un processore Cognitive Processor XR. Offre una luminosità superiore rispetto al modello precedente.'),
('Hisense U8K Mini-LED TV', 722.49, 2023, 'Hisense', 'TV', 'TV rilasciata nel 2023 da Hisense. Presenta un display Mini-LED 4K (3840 x 2160) e un processore Hi-View Engine. Offre un''ottima luminosità e un buon rapporto qualità-prezzo.'),
('TCL QM8 Mini-LED TV', 722.49, 2023, 'TCL', 'TV', 'TV rilasciata nel 2023 da TCL. Presenta un display Mini-LED 4K (3840 x 2160) e un processore AIPQ Engine Gen 3. Offre una luminosità elevata e un''ottima gestione della retroilluminazione.'),
('Apple Watch SE 2a generazione', 150.22, 2022, 'Apple', 'SMARTWATCH', 'Smartwatch rilasciato nel 2022 da Apple. Si presenta con un design simile al modello Serie 8. Monta un processore S8, lo stesso del modello più costoso. Offre le funzionalità principali di un Apple Watch, come il rilevamento delle cadute e il monitoraggio delle attività. La batteria garantisce un''autonomia fino a 18 ore.'),
('Apple Watch Serie 8', 200.70, 2022, 'Apple', 'SMARTWATCH', 'Smartwatch rilasciato nel 2022 da Apple. Si presenta con un design simile al modello precedente, ma offre nuove funzionalità di monitoraggio della salute, come il sensore di temperatura corporea e il rilevamento degli incidenti. Monta un processore S8. La batteria garantisce un''autonomia fino a 18 ore.'),
('Apple Watch Serie 9', 289.99, 2023, 'Apple', 'SMARTWATCH', 'Smartwatch rilasciato nel 2023 da Apple. Si presenta con un design simile al modello precedente, ma monta un processore S9 più veloce. Offre nuove gesture, come il doppio tocco, per interagire con il dispositivo.'),
('Apple Watch Serie 10', 399.99, 2024, 'Apple', 'SMARTWATCH', 'Smartwatch rilasciato nel 2024 da Apple. Si presenta con un design rivisitato e un display più grande. Monta un processore S10 più veloce e offre nuove funzionalità di monitoraggio della salute, come il monitoraggio non invasivo del glucosio nel sangue e la misurazione della pressione sanguigna. La batteria garantisce un''autonomia prolungata.'),
('Apple Watch Ultra', 399.99, 2022, 'Apple', 'SMARTWATCH', 'Smartwatch rilasciato nel 2022 da Apple. Si presenta con una cassa in titanio e un display più grande e resistente. Monta un processore S8 e offre funzionalità avanzate per gli sport estremi e per le immersioni. La batteria dura fino a 36 ore.'),
('Apple Watch Ultra 2', 799.99, 2024, 'Apple', 'SMARTWATCH', 'Smartwatch rilasciato nel 2023 da Apple. Si presenta con una cassa in titanio e un display più luminoso rispetto al modello precedente. Monta un processore S9 e offre funzionalità avanzate per gli sport all''aria aperta e per le immersioni. La batteria dura fino a 36 ore.'),
('Samsung Galaxy Watch 6', 289.99, 2023, 'Samsung', 'SMARTWATCH', 'Smartwatch rilasciato nel 2023 da Samsung. Si presenta con un design elegante e una ghiera sottile. Monta il processore Exynos W930 e offre funzionalità di monitoraggio del sonno e della composizione corporea. La batteria garantisce un''autonomia fino a 40 ore.'),
('Samsung Galaxy Watch 6 Classic', 361.24, 2023, 'Samsung', 'SMARTWATCH', 'Smartwatch rilasciato nel 2023 da Samsung. Si presenta con un design elegante e una ghiera rotante fisica per navigare nell''interfaccia. Monta il processore Exynos W930 e offre le stesse funzionalità di monitoraggio del modello base.'),
('Google Pixel Watch 2', 288.99, 2023, 'Google', 'SMARTWATCH', 'Smartwatch rilasciato nel 2023 da Google. Si presenta con un design circolare e una cassa in alluminio. Monta un processore Qualcomm Snapdragon W5+ Gen 1 e offre funzionalità di monitoraggio della salute e del fitness.'),
('Fitbit Sense 2', 184.23, 2022, 'Fitbit', 'SMARTWATCH', 'Smartwatch rilasciato nel 2022. Si presenta con un design elegante e offre funzionalità di monitoraggio dello stress e della salute. La batteria ha un''autonomia fino a 6 giorni.'),
('Garmin Venu 2 Plus', 245.64, 2022, 'Garmin', 'SMARTWATCH', 'Smartwatch rilasciato nel 2022 da Garmin. Si presenta con un design elegante e offre funzionalità avanzate per il fitness e il monitoraggio della salute. La batteria ha un''autonomia fino a 9 giorni.'),
('Fossil Gen 6', 156.60, 2021, 'Fossil', 'SMARTWATCH', 'Smartwatch rilasciato nel 2022 da Fossil. Si presenta con un design classico. Monta il processore Snapdragon Wear 4100+ e offre funzionalità di monitoraggio della salute e del fitness. La batteria si ricarica velocemente.');

UPDATE Prodotto SET image_path = nome || '.jpg';

UPDATE Prodotto SET prezzo = 1139.00 WHERE nome = 'iPhone 16 Pro Max';
UPDATE Prodotto SET prezzo = 999.00 WHERE nome = 'iPhone 16 Pro';
UPDATE Prodotto SET prezzo = 812.71 WHERE nome = 'iPhone 16 Plus';
UPDATE Prodotto SET prezzo = 539.00 WHERE nome = 'iPhone 16';
UPDATE Prodotto SET prezzo = 999.00 WHERE nome = 'iPhone 15 Pro Max';
UPDATE Prodotto SET prezzo = 875.00 WHERE nome = 'iPhone 15 Pro';
UPDATE Prodotto SET prezzo = 626.99 WHERE nome = 'iPhone 15 Plus';
UPDATE Prodotto SET prezzo = 579.00 WHERE nome = 'iPhone 15';
UPDATE Prodotto SET prezzo = 729.00 WHERE nome = 'iPhone 14 Pro Max';
UPDATE Prodotto SET prezzo = 649.00 WHERE nome = 'iPhone 14 Pro';
UPDATE Prodotto SET prezzo = 579.00 WHERE nome = 'iPhone 14 Plus';
UPDATE Prodotto SET prezzo = 439.99 WHERE nome = 'iPhone 14';
UPDATE Prodotto SET prezzo = 874.00 WHERE nome = 'Galaxy S25 Ultra';
UPDATE Prodotto SET prezzo = 599.00 WHERE nome = 'Galaxy S25+';
UPDATE Prodotto SET prezzo = 543.58 WHERE nome = 'Galaxy S25';
UPDATE Prodotto SET prezzo = 699.99 WHERE nome = 'Galaxy S24 Ultra';
UPDATE Prodotto SET prezzo = 659.99 WHERE nome = 'Galaxy S24+';
UPDATE Prodotto SET prezzo = 439.00 WHERE nome = 'Galaxy S24';
UPDATE Prodotto SET prezzo = 464.99 WHERE nome = 'Galaxy S23 Ultra';
UPDATE Prodotto SET prezzo = 317.58 WHERE nome = 'Galaxy S23+';
UPDATE Prodotto SET prezzo = 329.99 WHERE nome = 'Galaxy S23';
UPDATE Prodotto SET prezzo = 704.99 WHERE nome = 'Galaxy Z Fold 4';
UPDATE Prodotto SET prezzo = 419.99 WHERE nome = 'Galaxy Z Flip 4';
UPDATE Prodotto SET prezzo = 799.99 WHERE nome = 'Galaxy Z Fold 5';
UPDATE Prodotto SET prezzo = 429.00 WHERE nome = 'Galaxy Z Flip 5';
UPDATE Prodotto SET prezzo = 1069.00 WHERE nome = 'Galaxy Z Fold 6';
UPDATE Prodotto SET prezzo = 399.00 WHERE nome = 'Galaxy Z Flip 6';
UPDATE Prodotto SET prezzo = 1212.53 WHERE nome = 'Galaxy Z Fold 7';
UPDATE Prodotto SET prezzo = 736.64 WHERE nome = 'Galaxy Z Flip 7';
UPDATE Prodotto SET prezzo = 409.99 WHERE nome = 'Pixel 7';
UPDATE Prodotto SET prezzo = 329.99 WHERE nome = 'Pixel 7 Pro';
UPDATE Prodotto SET prezzo = 386.00 WHERE nome = 'Pixel 8';
UPDATE Prodotto SET prezzo = 469.99 WHERE nome = 'Pixel 8 Pro';
UPDATE Prodotto SET prezzo = 514.00 WHERE nome = 'Pixel 9';
UPDATE Prodotto SET prezzo = 757.00 WHERE nome = 'Pixel 9 Pro';
UPDATE Prodotto SET prezzo = 745.00 WHERE nome = 'MacBook Air M2';
UPDATE Prodotto SET prezzo = 2440.00 WHERE nome = 'MacBook Pro M2';
UPDATE Prodotto SET prezzo = 848.80 WHERE nome = 'MacBook Air M3';
UPDATE Prodotto SET prezzo = 1510.00 WHERE nome = 'MacBook Pro M3';
UPDATE Prodotto SET prezzo = 1140.00 WHERE nome = 'MacBook Air M4';
UPDATE Prodotto SET prezzo = 1459.00 WHERE nome = 'MacBook Pro M4';
UPDATE Prodotto SET prezzo = 1186.51 WHERE nome = 'Dell XPS 13';
UPDATE Prodotto SET prezzo = 1393.16 WHERE nome = 'Dell XPS 15';
UPDATE Prodotto SET prezzo = 1670.00 WHERE nome = 'Dell XPS 17';
UPDATE Prodotto SET prezzo = 2230.18 WHERE nome = 'Dell Latitude 9440 2-in-1';
UPDATE Prodotto SET prezzo = 759.99 WHERE nome = 'Dell G15 Gaming Laptop';
UPDATE Prodotto SET prezzo = 1457.18 WHERE nome = 'HP Spectre x360 14';
UPDATE Prodotto SET prezzo = 2015.85 WHERE nome = 'HP Envy x360 15';
UPDATE Prodotto SET prezzo = 849.99 WHERE nome = 'HP Omen 16 Gaming Laptop';
UPDATE Prodotto SET prezzo = 159.00 WHERE nome = 'HP Chromebook x360 14c';
UPDATE Prodotto SET prezzo = 1595.16 WHERE nome = 'Lenovo Yoga 9i';
UPDATE Prodotto SET prezzo = 1112.00 WHERE nome = 'Lenovo ThinkPad X1 Carbon Gen 11';
UPDATE Prodotto SET prezzo = 2129.01 WHERE nome = 'Lenovo Legion 5i Pro Gen 8';
UPDATE Prodotto SET prezzo = 191.50 WHERE nome = 'Lenovo Chromebook Duet 5';
UPDATE Prodotto SET prezzo = 350.00 WHERE nome = 'iPad 10a generazione';
UPDATE Prodotto SET prezzo = 727.13 WHERE nome = 'iPad Air 5a generazione';
UPDATE Prodotto SET prezzo = 704.50 WHERE nome = 'iPad Pro M2';
UPDATE Prodotto SET prezzo = 550.00 WHERE nome = 'iPad Mini 6a generazione';
UPDATE Prodotto SET prezzo = 549.00 WHERE nome = 'iPad Air M2';
UPDATE Prodotto SET prezzo = 481.66 WHERE nome = 'Galaxy Tab S8';
UPDATE Prodotto SET prezzo = 501.96 WHERE nome = 'Galaxy Tab S8+';
UPDATE Prodotto SET prezzo = 1099.00 WHERE nome = 'Galaxy Tab S8 Ultra';
UPDATE Prodotto SET prezzo = 402.50 WHERE nome = 'Galaxy Tab S9';
UPDATE Prodotto SET prezzo = 606.50 WHERE nome = 'Galaxy Tab S9+';
UPDATE Prodotto SET prezzo = 1090.41 WHERE nome = 'Galaxy Tab S9 Ultra';
UPDATE Prodotto SET prezzo = 350.00 WHERE nome = 'Galaxy Tab S10';
UPDATE Prodotto SET prezzo = 500.00 WHERE nome = 'Galaxy Tab S10+';
UPDATE Prodotto SET prezzo = 900.00 WHERE nome = 'Galaxy Tab S10 Ultra';
UPDATE Prodotto SET prezzo = 240.00 WHERE nome = 'AirPods Pro 2a gen';
UPDATE Prodotto SET prezzo = 140.00 WHERE nome = 'Samsung Galaxy Buds2 Pro';
UPDATE Prodotto SET prezzo = 180.00 WHERE nome = 'Google Pixel Buds Pro';
UPDATE Prodotto SET prezzo = 300.00 WHERE nome = 'Sony WH-1000XM5';
UPDATE Prodotto SET prezzo = 125.00 WHERE nome = 'Sony PlayStation 3D Pulse';
UPDATE Prodotto SET prezzo = 300.00 WHERE nome = 'Bose QuietComfort 45';
UPDATE Prodotto SET prezzo = 530.00 WHERE nome = 'AirPods Max';
UPDATE Prodotto SET prezzo = 250.00 WHERE nome = 'Beats Studio3 Wireless';
UPDATE Prodotto SET prezzo = 170.00 WHERE nome = 'Sonos Era 100';
UPDATE Prodotto SET prezzo = 270.00 WHERE nome = 'Sonos Era 300';
UPDATE Prodotto SET prezzo = 70.00 WHERE nome = 'Amazon Echo (4a gen)';
UPDATE Prodotto SET prezzo = 80.00 WHERE nome = 'Google Nest Audio';
UPDATE Prodotto SET prezzo = 95.00 WHERE nome = 'HomePod mini';
UPDATE Prodotto SET prezzo = 40.00 WHERE nome = 'Amazon Echo Dot (5a gen)';
UPDATE Prodotto SET prezzo = 35.00 WHERE nome = 'Google Nest Mini (2a gen)';
UPDATE Prodotto SET prezzo = 100.00 WHERE nome = 'HomePod (1a gen)';
UPDATE Prodotto SET prezzo = 480.00 WHERE nome = 'PlayStation 5';
UPDATE Prodotto SET prezzo = 405.00 WHERE nome = 'PlayStation 5 Digital Edition';
UPDATE Prodotto SET prezzo = 720.00 WHERE nome = 'PlayStation 5 Pro';
UPDATE Prodotto SET prezzo = 180.00 WHERE nome = 'PlayStation 4';
UPDATE Prodotto SET prezzo = 260.00 WHERE nome = 'PlayStation 4 Pro';
UPDATE Prodotto SET prezzo = 190.00 WHERE nome = 'PlayStation 4 Slim';
UPDATE Prodotto SET prezzo = 500.00 WHERE nome = 'Xbox Series X';
UPDATE Prodotto SET prezzo = 300.00 WHERE nome = 'Xbox Series S';
UPDATE Prodotto SET prezzo = 230.00 WHERE nome = 'Xbox One X';
UPDATE Prodotto SET prezzo = 190.00 WHERE nome = 'Xbox One S';
UPDATE Prodotto SET prezzo = 320.00 WHERE nome = 'Nintendo Switch';
UPDATE Prodotto SET prezzo = 180.00 WHERE nome = 'Nintendo Switch Lite';
UPDATE Prodotto SET prezzo = 350.00 WHERE nome = 'Nintendo Switch OLED';
UPDATE Prodotto SET prezzo = 400.00 WHERE nome = 'Nintendo Switch 2';
UPDATE Prodotto SET prezzo = 1500.00 WHERE nome = 'Apple Studio Display';
UPDATE Prodotto SET prezzo = 5400.00 WHERE nome = 'Apple Pro Display XDR';
UPDATE Prodotto SET prezzo = 900.00 WHERE nome = 'LG UltraGear OLED';
UPDATE Prodotto SET prezzo = 1400.00 WHERE nome = 'Samsung Odyssey Neo G9';
UPDATE Prodotto SET prezzo = 1200.00 WHERE nome = 'Samsung ViewFinity S9';
UPDATE Prodotto SET prezzo = 1150.00 WHERE nome = 'Dell Alienware AW3423DW';
UPDATE Prodotto SET prezzo = 1200.00 WHERE nome = 'LG C3 OLED TV';
UPDATE Prodotto SET prezzo = 1400.00 WHERE nome = 'Samsung S95C OLED TV';
UPDATE Prodotto SET prezzo = 1000.00 WHERE nome = 'Samsung QN90C Neo QLED TV';
UPDATE Prodotto SET prezzo = 1600.00 WHERE nome = 'Sony A95K QD-OLED TV';
UPDATE Prodotto SET prezzo = 1800.00 WHERE nome = 'Sony Bravia XR A95L OLED';
UPDATE Prodotto SET prezzo = 900.00 WHERE nome = 'Hisense U8K Mini-LED TV';
UPDATE Prodotto SET prezzo = 850.00 WHERE nome = 'TCL QM8 Mini-LED TV';
UPDATE Prodotto SET prezzo = 300.00 WHERE nome = 'Apple Watch SE 2a gen';
UPDATE Prodotto SET prezzo = 400.00 WHERE nome = 'Apple Watch Serie 8';
UPDATE Prodotto SET prezzo = 450.00 WHERE nome = 'Apple Watch Serie 9';
UPDATE Prodotto SET prezzo = 800.00 WHERE nome = 'Apple Watch Ultra';
UPDATE Prodotto SET prezzo = 350.00 WHERE nome = 'Samsung Galaxy Watch 6';
UPDATE Prodotto SET prezzo = 400.00 WHERE nome = 'Samsung Galaxy Watch 6 Classic';
UPDATE Prodotto SET prezzo = 300.00 WHERE nome = 'Google Pixel Watch 2';
UPDATE Prodotto SET prezzo = 250.00 WHERE nome = 'Fitbit Sense 2';
UPDATE Prodotto SET prezzo = 350.00 WHERE nome = 'Garmin Venu 2 Plus';
UPDATE Prodotto SET prezzo = 220.00 WHERE nome = 'Fossil Gen 6';